FROM debian:stable

WORKDIR /workspace/scratch
ADD . /workspace/scratch/
RUN apt-get update \
	&& apt-get install -y make dpkg-dev debhelper git-core \
	&& make debian-changelog && rm Makefile \
	&& dpkg-buildpackage -b -us -uc

VOLUME /output
CMD cp /workspace/*.deb /output/
