#!/usr/bin/env sh
set -eu

install_dir="${TARGET:-/usr/local/bin}"
version="${VERSION:-1.0.1}"
DOWNLOAD="https://github.com/smartystreets/version-tools/releases/download/${version}/release.tar.gz"

mkdir -p "${install_dir}"

if command -v curl > /dev/null; then
  curl -sL "${DOWNLOAD}" | tar -xzo -C "${install_dir}"
elif command -v wget > /dev/null; then
  wget -q -O - "${DOWNLOAD}" | tar -xzo -C "${install_dir}"
else
  echo "wget or curl must be installed." && exit 1
fi

chmod 0755 "${install_dir}/bumpit" "${install_dir}/tagit"

echo "Package [version-tools@${version}] successfully installed into [${install_dir}]."
