#!/usr/bin/env sh
set -e

if test "x${1}" = "x" || test "x${2}" = "x"; then
   echo "usage: $(basename ${0}) [-Mmp] major.minor.patch" && exit 1
fi

while getopts ":Mmp" bump; do
  case $bump in
    M) bump_major=true;;
    m) bump_minor=true;;
    p) bump_patch=true;;
  esac
done

clean=$(echo "${2}" | awk '{split($0,a,"-"); print a[1]}')
major=$(echo "${clean}" | awk '{split($0,a,"."); print a[1]}')
minor=$(echo "${clean}" | awk '{split($0,a,"."); print a[2]}')
patch=$(echo "${clean}" | awk '{split($0,a,"."); print a[3]}')

[ ! -z ${bump_major} ] && major=$((major+1)) && minor=0 && patch=0
[ ! -z ${bump_minor} ] && minor=$((minor+1)) && patch=0
[ ! -z ${bump_patch} ] && patch=$((patch+1))

echo "${major}.${minor}.${patch}"
