#!/usr/bin/env sh
set -e

case "${1}" in
  -M|-m|-p) ;;
  *) echo "usage: $(basename ${0}) -[M|m|p]" && exit 1
esac

message="Git command not found. Git executable is required to tag git repositories."
command -v git >/dev/null 2>/dev/null || (echo "${message}" && exit 2)

message="Git repository not found. This command must be run within a git repository."
git rev-parse --git-dir >/dev/null 2>/dev/null || (echo "${message}" && exit 3)

version="$(git describe --tags 2>/dev/null || echo "0.0.0")"
bump="$(dirname "${0}")/bumpit"
clean="$("${bump}" -${1} "${version}")"
dirty="$("${bump}" -${1} "${version}" --dirty)"

message="No changes to repository since last tag '${dirty}'."
test "x${clean}" != "x${dirty}" && echo "${message}" && exit 0

message="Unable to tag the repository with version '${clean}'. The tag already exists."
git rev-parse "${clean}" >/dev/null 2>/dev/null && (echo "${message}" && exit 4)

message="Unable to tag repository with version '${clean}'. Does your user environment have your .gitconfig set with user.name and user.email?"
git tag -a "${clean}" -m "" 2>/dev/null || (echo "${message}" && exit 5)

echo "Tagged repository with version '${clean}'."
